# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Features
      labels:
        - feat
        - feature
        - enhancement
    - title: 🐛 Fixes
      labels:
        - fix
        - bug
    - title: 🧪 Tests
      labels:
        - test
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 📚 Documentation
      labels:
        - docs
    - title: 💬 Other
      labels:
        - "*"

